Repository DeveloperAcademy-POSTECH/MC3-Team3-Kongs, pull requests merged in 2022-07, with the labels that each got.

#9 [ADD] 데이터 모델
  Hypeclass.xcodeproj/project.pbxproj
  Hypeclass/Model/DanceClass.swift
  Hypeclass/Model/Dancer.swift
  Hypeclass/Model/Genre.swift
  Hypeclass/Model/Studio.swift
Labels: 🧑🏻‍💻 루크, 🗃 model

#24 [ADD] SearchView 관련 파일 생성
  Hypeclass.xcodeproj/project.pbxproj
  Hypeclass/Source/Main/SearchDetailViewController.swift
  Hypeclass/Source/Main/SearchViewController.swift
Labels: 🧑🏻‍💻 치콩, 🎨 UI

#32 [FEAT] 날짜 관련 뷰 구현
  Hypeclass.xcodeproj/project.pbxproj
  Hypeclass/Config/Base/BaseViewController.swift
  Hypeclass/Model/DanceClass.swift
  Hypeclass/Model/Dancer.swift
  Hypeclass/Model/Genre.swift
  Hypeclass/Model/Studio.swift
  Hypeclass/SceneDelegate.swift
  Hypeclass/Source/Schedule/ScheduleViewController.swift
  Hypeclass/Source/Schedule/WeekdayView.swift
  Hypeclass/Util/Extension/Date.swift
  Hypeclass/Util/Extension/UIColor.swift
Labels: 🧑🏻‍💻 지오, 🎨 UI, 🗃 model

#36 [FEAT] 탭바 컬러 변경 및 네비게이션 공통 사항 업데이트
  Hypeclass.xcodeproj/project.pbxproj
  Hypeclass/Config/Base/BaseViewController.swift
  Hypeclass/Info.plist
  Hypeclass/Source/MainTabController.swift
Labels: 🧑🏻‍💻 루크, 🎨 UI

#37 [FEAT] scheduleCollectionView 구현
  Hypeclass.xcodeproj/project.pbxproj
  Hypeclass/Source/Schedule/ScheduleButton.swift
  Hypeclass/Source/Schedule/ScheduleViewController.swift
  Hypeclass/Source/Schedule/WeekdayView.swift
Labels: 🧑🏻‍💻 지오, 🎨 UI

#38 [FEAT] UISearchBar 구현
  Hypeclass.xcodeproj/project.pbxproj
  Hypeclass/Config/Base/BaseViewController.swift
  Hypeclass/Info.plist
  Hypeclass/Model/DanceClass.swift
  Hypeclass/Model/Dancer.swift
  Hypeclass/Model/Genre.swift
  Hypeclass/Model/Studio.swift
  Hypeclass/SceneDelegate.swift
  Hypeclass/Source/Main/SearchDetailViewController.swift
  Hypeclass/Source/Main/SearchViewController.swift
  Hypeclass/Source/MainTabController.swift
  Hypeclass/Util/Extension/UIColor.swift
Labels: 🧑🏻‍💻 치콩, 🎨 UI

#39 merge feature/schedule to develop
  Hypeclass.xcodeproj/project.pbxproj
  Hypeclass/Model/DanceClass.swift
  Hypeclass/Source/Schedule/ScheduleButton.swift
  Hypeclass/Source/Schedule/ScheduleViewController.swift
  Hypeclass/Source/Schedule/WeekdayView.swift
  Hypeclass/Util/Extension/Date.swift
Labels: ↰ Merge

#42 merge Feature/search to develop
  Hypeclass.xcodeproj/project.pbxproj
  Hypeclass/Source/Main/SearchDetailViewController.swift
  Hypeclass/Source/Main/SearchViewController.swift
Labels: ↰ Merge, 🚧 Conflict

#44 [Design] UISearchBar Design 변경
  Hypeclass.xcodeproj/project.pbxproj
  Hypeclass/Source/Main/SearchDetailViewController.swift
  Hypeclass/Source/Main/SearchViewController.swift
  Hypeclass/Util/Extension/UIColor.swift
  Hypeclass/Util/SearchBar.swift
Labels: 🧑🏻‍💻 치콩, 🎨 UI

#45 [REFACTOR] WeekdayView 삭제, WeekdayCell 추가, CollectionView로 구조 수정
  Hypeclass.xcodeproj/project.pbxproj
  Hypeclass/Config/Base/BaseViewController.swift
  Hypeclass/Info.plist
  Hypeclass/Model/Weekday.swift
  Hypeclass/Source/Main/SearchDetailViewController.swift
  Hypeclass/Source/Main/SearchViewController.swift
  Hypeclass/Source/MainTabController.swift
  Hypeclass/Source/Schedule/ScheduleViewController.swift
  Hypeclass/Source/Schedule/WeekdayCell.swift
  Hypeclass/Source/Schedule/WeekdayView.swift
Labels: 🧑🏻‍💻 지오, 🛠 Refactor

#47 [ADD] Dancer, DanceClass Mock JSON Data Set 추가 , Codable 파싱 메서드 구현
  Hypeclass.xcodeproj/project.pbxproj
  Hypeclass/Model/DanceClass.json
  Hypeclass/Model/DanceClass.swift
  Hypeclass/Model/Dancer.json
  Hypeclass/Model/Dancer.swift
  Hypeclass/Model/MockDataSet.swift
  Hypeclass/Model/Studio.swift
Labels: 🧑🏻‍💻 루크, 🗃 Model

#51 merge Feature/schedule -> develop
  Hypeclass.xcodeproj/project.pbxproj
  Hypeclass/Model/Weekday.swift
  Hypeclass/Source/Schedule/ScheduleViewController.swift
  Hypeclass/Source/Schedule/WeekdayCell.swift
  Hypeclass/Source/Schedule/WeekdayView.swift
Labels: 🧑🏻‍💻 루크, ↰ Merge

#49 [FEAT] DancerDetailView 커버사진 구현
  Hypeclass.xcodeproj/project.pbxproj
  Hypeclass/Assets.xcassets/DancerCoverImage.imageset/Contents.json
  Hypeclass/Assets.xcassets/DancerCoverImage.imageset/DancerCoverImage.png
  Hypeclass/Config/Base/BaseViewController.swift
  Hypeclass/Info.plist
  Hypeclass/Model/DanceClass.swift
  Hypeclass/Model/Dancer.swift
  Hypeclass/Model/Genre.swift
  Hypeclass/Model/Studio.swift
  Hypeclass/SceneDelegate.swift
  Hypeclass/Source/DancerDetailView.swift
  Hypeclass/Source/Main/SearchDetailViewController.swift
  Hypeclass/Source/Main/SearchViewController.swift
  Hypeclass/Source/MainTabController.swift
  Hypeclass/Source/Schedule/ScheduleButton.swift
  Hypeclass/Source/Schedule/ScheduleViewController.swift
  Hypeclass/Source/Schedule/WeekdayView.swift
  Hypeclass/Util/Extension/Date.swift
  Hypeclass/Util/Extension/UIColor.swift
Labels: 🧑🏻‍💻 이안, 🎨 UI

#50 [FEAT] titleLabel searchButton view 구현
  Hypeclass.xcodeproj/project.pbxproj
  Hypeclass/Config/Base/BaseViewController.swift
  Hypeclass/Info.plist
  Hypeclass/Model/DanceClass.swift
  Hypeclass/Model/Dancer.swift
  Hypeclass/Model/Genre.swift
  Hypeclass/Model/Studio.swift
  Hypeclass/SceneDelegate.swift
  Hypeclass/Source/Main/MainViewController.swift
  Hypeclass/Source/Main/SearchDetailViewController.swift
  Hypeclass/Source/Main/SearchViewController.swift
  Hypeclass/Source/MainTabController.swift
  Hypeclass/Source/Schedule/ScheduleButton.swift
  Hypeclass/Source/Schedule/ScheduleViewController.swift
  Hypeclass/Source/Schedule/WeekdayView.swift
  Hypeclass/Util/Extension/Date.swift
  Hypeclass/Util/Extension/UIColor.swift
Labels: 🧑🏻‍💻 레이븐, 🎨 UI

#53 [FEAT] ScheduleViewController 데이터 연결
  Hypeclass/Source/Schedule/ScheduleViewController.swift
  Hypeclass/Util/Extension/Date.swift
Labels: 🧑🏻‍💻 지오, 🎨 UI

#54 [FEAT] DancerDetailView 댄서 프로필 구현
  Hypeclass.xcodeproj/project.pbxproj
  Hypeclass/Assets.xcassets/DancerInstagramImage.imageset/Contents.json
  Hypeclass/Assets.xcassets/DancerInstagramImage.imageset/image 54.png
  Hypeclass/Assets.xcassets/DancerProfileImage.imageset/Contents.json
  Hypeclass/Assets.xcassets/DancerProfileImage.imageset/Mask group.png
  Hypeclass/Model/DanceClass.json
  Hypeclass/Model/DanceClass.swift
  Hypeclass/Model/Dancer.json
  Hypeclass/Model/Dancer.swift
  Hypeclass/Model/MockDataSet.swift
  Hypeclass/Model/Studio.swift
  Hypeclass/Model/Weekday.swift
  Hypeclass/SceneDelegate.swift
  Hypeclass/Source/DancerDetailView.swift
  Hypeclass/Source/Schedule/ScheduleViewController.swift
  Hypeclass/Source/Schedule/WeekdayCell.swift
  Hypeclass/Source/Schedule/WeekdayView.swift
Labels: 🧑🏻‍💻 이안, 🎨 UI

#56 [FEAT] 최근 검색어 기록 구현
  Hypeclass.xcodeproj/project.pbxproj
  Hypeclass/Config/ReusableComponent/SearchBar.swift
  Hypeclass/Config/ReusableComponent/Separator.swift
  Hypeclass/Source/Main/SearchDetailViewController.swift
  Hypeclass/Source/Main/SearchViewController.swift
  Hypeclass/Source/Search/HistoryCell.swift
  Hypeclass/Source/Search/SearchDetailViewController.swift
  Hypeclass/Source/Search/SearchViewController.swift
Labels: 🧑🏻‍💻 치콩, 🎨 UI

#63 merge Feature/search -> develop
  Hypeclass.xcodeproj/project.pbxproj
  Hypeclass/Config/ReusableComponent/SearchBar.swift
  Hypeclass/Config/ReusableComponent/Separator.swift
  Hypeclass/Source/Main/SearchDetailViewController.swift
  Hypeclass/Source/Main/SearchViewController.swift
  Hypeclass/Source/Search/HistoryCell.swift
  Hypeclass/Source/Search/SearchDetailViewController.swift
  Hypeclass/Source/Search/SearchViewController.swift
Labels: 🧑🏻‍💻 루크, ↰ Merge

#64 merge Feature/schedule -> develop
  Hypeclass/Source/Schedule/ScheduleViewController.swift
  Hypeclass/Util/Extension/Date.swift
Labels: 🧑🏻‍💻 루크, ↰ Merge

#60 [REFACTOR] ScheduleButton -> ScheduleView
  Hypeclass.xcodeproj/project.pbxproj
  Hypeclass/Model/DanceClass.json
  Hypeclass/Model/DanceClass.swift
  Hypeclass/Model/Dancer.json
  Hypeclass/Model/Dancer.swift
  Hypeclass/Model/Studio.swift
  Hypeclass/Source/Main/SearchDetailViewController.swift
  Hypeclass/Source/Main/SearchViewController.swift
  Hypeclass/Source/Schedule/ScheduleButton.swift
  Hypeclass/Source/Schedule/ScheduleView.swift
  Hypeclass/Source/Schedule/ScheduleViewController.swift
  Hypeclass/Source/Schedule/WeekdayCell.swift
  Hypeclass/Util/Extension/UIColor.swift
  Hypeclass/Util/SearchBar.swift
Labels: 🧑🏻‍💻 지오, 🎨 UI, 🛠 Refactor

#62 [FEAT] Genre UICollectionView 구현
  Hypeclass.xcodeproj/project.pbxproj
  Hypeclass/Source/Main/MainViewController+GenreCell.swift
  Hypeclass/Source/Main/MainViewController.swift
Labels: 🧑🏻‍💻 레이븐, 🎨 UI

#67 [DESIGN] tableViewCell의 배경색 background 컬러로 변경 및 코드리뷰 변경
  Hypeclass.xcodeproj/project.pbxproj
  Hypeclass/Config/ReusableComponent/SearchBar.swift
  Hypeclass/Config/ReusableComponent/Separator.swift
  Hypeclass/Model/DanceClass.json
  Hypeclass/Model/DanceClass.swift
  Hypeclass/Model/Dancer.json
  Hypeclass/Model/Dancer.swift
  Hypeclass/Model/Studio.swift
  Hypeclass/Source/Main/SearchDetailViewController.swift
  Hypeclass/Source/Main/SearchViewController.swift
  Hypeclass/Source/Schedule/ScheduleViewController.swift
  Hypeclass/Source/Search/HistoryCell.swift
  Hypeclass/Source/Search/SearchDetailViewController.swift
  Hypeclass/Source/Search/SearchViewController.swift
  Hypeclass/Source/Subscription/DancerCell.swift
  Hypeclass/Source/Subscription/SubscriptionViewController.swift
  Hypeclass/Util/Extension/Date.swift
Labels: 👩🏻‍💻 니아, 🎨 UI

#69 merge Feature/subscription -> main
  Hypeclass.xcodeproj/project.pbxproj
  Hypeclass/Config/Base/BaseViewController.swift
  Hypeclass/Config/ReusableComponent/SearchBar.swift
  Hypeclass/Config/ReusableComponent/Separator.swift
  Hypeclass/Info.plist
  Hypeclass/Model/DanceClass.json
  Hypeclass/Model/DanceClass.swift
  Hypeclass/Model/Dancer.json
  Hypeclass/Model/Dancer.swift
  Hypeclass/Model/Genre.swift
  Hypeclass/Model/MockDataSet.swift
  Hypeclass/Model/Studio.swift
  Hypeclass/Model/Weekday.swift
  Hypeclass/SceneDelegate.swift
  Hypeclass/Source/MainTabController.swift
  Hypeclass/Source/Schedule/ScheduleButton.swift
  Hypeclass/Source/Schedule/ScheduleViewController.swift
  Hypeclass/Source/Schedule/WeekdayCell.swift
  Hypeclass/Source/Search/HistoryCell.swift
  Hypeclass/Source/Search/SearchDetailViewController.swift
  Hypeclass/Source/Search/SearchViewController.swift
  Hypeclass/Source/Subscription/DancerCell.swift
  Hypeclass/Source/Subscription/SubscriptionViewController.swift
  Hypeclass/Util/Extension/Date.swift
  Hypeclass/Util/Extension/UIColor.swift
Labels: 🧑🏻‍💻 루크, ↰ Merge

#72 merge Feature/search -> devleop
  Hypeclass.xcodeproj/project.pbxproj
  Hypeclass/Config/ReusableComponent/DancerCell.swift
  Hypeclass/Source/Search/SearchDetailCell.swift
  Hypeclass/Source/Search/SearchDetailViewController.swift
  Hypeclass/Util/Extension/UIImageView.swift
Labels: 🧑🏻‍💻 루크, 🧑🏻‍💻 치콩, ↰ Merge, 🚧 Conflict

#75 merge Feature/detail -> develop
  Hypeclass.xcodeproj/project.pbxproj
  Hypeclass/Assets.xcassets/DancerCoverImage.imageset/Contents.json
  Hypeclass/Assets.xcassets/DancerCoverImage.imageset/DancerCoverImage.png
  Hypeclass/Assets.xcassets/DancerInstagramImage.imageset/Contents.json
  Hypeclass/Assets.xcassets/DancerInstagramImage.imageset/image 54.png
  Hypeclass/Assets.xcassets/DancerProfileImage.imageset/Contents.json
  Hypeclass/Assets.xcassets/DancerProfileImage.imageset/Mask group.png
  Hypeclass/Source/DancerDetailView.swift
Labels: 🧑🏻‍💻 루크, ↰ Merge, 🚧 Conflict

#77 [FEAT] Dancer UICollectionView 구현
  Hypeclass.xcodeproj/project.pbxproj
  Hypeclass/Assets.xcassets/DancerCoverImage.imageset/Contents.json
  Hypeclass/Assets.xcassets/DancerCoverImage.imageset/DancerCoverImage.png
  Hypeclass/Assets.xcassets/DancerInstagramImage.imageset/Contents.json
  Hypeclass/Assets.xcassets/DancerInstagramImage.imageset/image 54.png
  Hypeclass/Assets.xcassets/DancerProfileImage.imageset/Contents.json
  Hypeclass/Assets.xcassets/DancerProfileImage.imageset/Mask group.png
  Hypeclass/Config/ReusableComponent/DancerCell.swift
  Hypeclass/Config/ReusableComponent/SearchBar.swift
  Hypeclass/Config/ReusableComponent/Separator.swift
  Hypeclass/Model/DanceClass.json
  Hypeclass/Model/DanceClass.swift
  Hypeclass/Model/Dancer.json
  Hypeclass/Model/Dancer.swift
  Hypeclass/Model/MockDataSet.swift
  Hypeclass/Model/Studio.swift
  Hypeclass/Model/Weekday.swift
  Hypeclass/Source/DancerDetailView.swift
  Hypeclass/Source/Main/MainViewController+DancerCell.swift
  Hypeclass/Source/Main/MainViewController+GenreCell.swift
  Hypeclass/Source/Main/MainViewController.swift
  Hypeclass/Source/Main/SearchDetailViewController.swift
  Hypeclass/Source/Main/SearchViewController.swift
  Hypeclass/Source/Schedule/ScheduleButton.swift
  Hypeclass/Source/Schedule/ScheduleView.swift
  Hypeclass/Source/Schedule/ScheduleViewController.swift
  Hypeclass/Source/Schedule/WeekdayCell.swift
  Hypeclass/Source/Schedule/WeekdayView.swift
  Hypeclass/Source/Search/HistoryCell.swift
  Hypeclass/Source/Search/SearchDetailCell.swift
  Hypeclass/Source/Search/SearchDetailViewController.swift
  Hypeclass/Source/Search/SearchViewController.swift
  Hypeclass/Source/Subscription/DancerCell.swift
  Hypeclass/Source/Subscription/SubscriptionViewController.swift
  Hypeclass/Util/Extension/Date.swift
  Hypeclass/Util/Extension/UIColor.swift
  Hypeclass/Util/Extension/UIImageView.swift
Labels: 🧑🏻‍💻 레이븐, 🎨 UI

#76 merge Feature/home -> devleop
  Hypeclass.xcodeproj/project.pbxproj
  Hypeclass/Source/Main/MainViewController+DancerCell.swift
  Hypeclass/Source/Main/MainViewController+GenreCell.swift
  Hypeclass/Source/Main/MainViewController.swift
  Hypeclass/Source/MainTabController.swift
  Hypeclass/Source/Schedule/ScheduleViewController.swift
Labels: 🧑🏻‍💻 루크, 🧑🏻‍💻 레이븐, ↰ Merge, 🚧 Conflict

#78 [RENAME] DancerCell에서 SubDetailCell로 파일명 변경
  Hypeclass.xcodeproj/project.pbxproj
  Hypeclass/Source/Subscription/SubDetailCell.swift
Labels: 👩🏻‍💻 니아

#80 [FEAT] ViewController Intergration 작업
  Hypeclass.xcodeproj/project.pbxproj
  Hypeclass/Source/DancerDetailView.swift
  Hypeclass/Source/DancerDetailViewController.swift
  Hypeclass/Source/Main/MainViewController.swift
  Hypeclass/Source/Schedule/ScheduleViewController.swift
  Hypeclass/Source/Search/SearchDetailViewController.swift
  Hypeclass/Source/Subscription/SubscriptionViewController.swift
  Hypeclass/Source/WeeklyScheduleCell.swift
Labels: 🧑🏻‍💻 루크

#91 [ADD] Firebase 셋업
  Hypeclass.xcodeproj/project.pbxproj
  Hypeclass/API/Constant.swift
  Hypeclass/API/DanceClassManager.swift
  Hypeclass/API/DancerManager.swift
  Hypeclass/API/DancerService.swift
  Hypeclass/API/StudioManager.swift
  Hypeclass/Source/Schedule/ScheduleViewController.swift
  Hypeclass/Source/Search/SearchDetailViewController.swift
Labels: 🧑🏻‍💻 지오, 🌐 API

#85 [FEAT] DancerSchedule CollectionView 구현
  Hypeclass.xcodeproj/project.pbxproj
  Hypeclass/Assets.xcassets/DancerCoverImage.imageset/Contents.json
  Hypeclass/Assets.xcassets/DancerCoverImage.imageset/DancerCoverImage.png
  Hypeclass/Assets.xcassets/DancerCoverImage.imageset/Mask group.png
  Hypeclass/Assets.xcassets/DancerProfileImage.imageset/Contents.json
  Hypeclass/Assets.xcassets/DancerProfileImage.imageset/Mask group.png
  Hypeclass/Config/ReusableComponent/DancerCell.swift
  Hypeclass/Model/DancerDetailSchduleManager.swift
  Hypeclass/Model/DancerDetailScheduleModel.swift
  Hypeclass/SceneDelegate.swift
  Hypeclass/Source/DancerDetailView.swift
  Hypeclass/Source/DancerDetailViewController.swift
  Hypeclass/Source/Main/MainViewController+DancerCell.swift
  Hypeclass/Source/Main/MainViewController+GenreCell.swift
  Hypeclass/Source/Main/MainViewController.swift
  Hypeclass/Source/MainTabController.swift
  Hypeclass/Source/Schedule/ScheduleViewController.swift
  Hypeclass/Source/Search/SearchDetailCell.swift
  Hypeclass/Source/Search/SearchDetailViewController.swift
  Hypeclass/Source/Subscription/SubscriptionViewController.swift
  Hypeclass/Source/WeeklyScheduleCell.swift
  Hypeclass/Util/Extension/UIImageView.swift
Labels: 🧑🏻‍💻 이안, 🎨 UI

#92 [FEAT] Manager 기능 구현(async)
  Hypeclass/API/DanceClassManager.swift
  Hypeclass/API/DancerManager.swift
  Hypeclass/API/StudioManager.swift
Labels: 🧑🏻‍💻 지오, 🌐 API

#93 [FEAT] SearchManager 구현
  Hypeclass.xcodeproj/project.pbxproj
  Hypeclass/API/SearchManager.swift
  Hypeclass/Source/Search/SearchViewController.swift
Labels: 🧑🏻‍💻 치콩, 🌐 API

#97 [REFACTOR] ScheduleViewController Firebase 적용
  Hypeclass/API/DanceClassManager.swift
  Hypeclass/API/DancerManager.swift
  Hypeclass/Source/Schedule/ScheduleViewController.swift
Labels: 🧑🏻‍💻 지오, 🌐 API

#100 merge Feature/firebase -> develop
  Hypeclass.xcodeproj/project.pbxproj
  Hypeclass.xcodeproj/xcuserdata/gongtae.xcuserdatad/xcschemes/xcschememanagement.plist
  Hypeclass/API/Constant.swift
  Hypeclass/API/DanceClassManager.swift
  Hypeclass/API/DancerManager.swift
  Hypeclass/API/DancerService.swift
  Hypeclass/API/SearchManager.swift
  Hypeclass/API/StudioManager.swift
  Hypeclass/AppDelegate.swift
  Hypeclass/GoogleService-Info.plist
  Hypeclass/Model/DanceClass.swift
  Hypeclass/Model/Dancer.swift
  Hypeclass/Model/Studio.swift
  Hypeclass/Source/Schedule/ScheduleViewController.swift
  Hypeclass/Source/Search/SearchDetailViewController.swift
  Hypeclass/Source/Search/SearchViewController.swift
Labels: 🧑🏻‍💻 루크, ↰ Merge

#101 merge Feature/detail -> develop
  Hypeclass.xcodeproj/project.pbxproj
  Hypeclass/Assets.xcassets/DancerCoverImage.imageset/Contents.json
  Hypeclass/Assets.xcassets/DancerCoverImage.imageset/DancerCoverImage.png
  Hypeclass/Assets.xcassets/DancerCoverImage.imageset/Mask group.png
  Hypeclass/Assets.xcassets/DancerProfileImage.imageset/Contents.json
  Hypeclass/Assets.xcassets/DancerProfileImage.imageset/Mask group.png
  Hypeclass/Model/DancerDetailSchduleManager.swift
  Hypeclass/Model/DancerDetailScheduleModel.swift
  Hypeclass/SceneDelegate.swift
  Hypeclass/Source/DancerDetailViewController.swift
  Hypeclass/Source/WeeklyScheduleCell.swift
Labels: 🧑🏻‍💻 루크, ↰ Merge

#104 [FEAT] SubscriptionViewController 구현
  Hypeclass.xcodeproj/project.pbxproj
  Hypeclass/API/DancerManager.swift
  Hypeclass/API/StudioManager.swift
  Hypeclass/Source/Subscription/SubscriptionViewController.swift
  Hypeclass/Util/ReusableComponent/ItemCell.swift
Labels: 🧑🏻‍💻 지오, 🎨 UI, 🌐 API

#106 [FEAT] ScheduleViewController 구독한 댄서가 없을 때 뷰 구현
  Hypeclass.xcodeproj/project.pbxproj
  Hypeclass.xcodeproj/xcuserdata/gongtae.xcuserdatad/xcschemes/xcschememanagement.plist
  Hypeclass/API/Constant.swift
  Hypeclass/API/DanceClassManager.swift
  Hypeclass/API/DancerManager.swift
  Hypeclass/API/DancerService.swift
  Hypeclass/API/SearchManager.swift
  Hypeclass/API/StudioManager.swift
  Hypeclass/AppDelegate.swift
  Hypeclass/Assets.xcassets/DancerCoverImage.imageset/Contents.json
  Hypeclass/Assets.xcassets/DancerCoverImage.imageset/Mask group.png
  Hypeclass/Assets.xcassets/DancerInstagramImage.imageset/Contents.json
  Hypeclass/Assets.xcassets/DancerInstagramImage.imageset/image 54.png
  Hypeclass/Assets.xcassets/DancerProfileImage.imageset/Contents.json
  Hypeclass/Assets.xcassets/DancerProfileImage.imageset/Mask group.png
  Hypeclass/GoogleService-Info.plist
  Hypeclass/Model/DanceClass.swift
  Hypeclass/Model/Dancer.swift
  Hypeclass/Model/DancerDetailSchduleManager.swift
  Hypeclass/Model/DancerDetailScheduleModel.swift
  Hypeclass/Model/Studio.swift
  Hypeclass/Source/DancerDetailViewController.swift
  Hypeclass/Source/Main/MainViewController+DancerCell.swift
  Hypeclass/Source/Main/MainViewController+GenreCell.swift
  Hypeclass/Source/Main/MainViewController.swift
  Hypeclass/Source/MainTabController.swift
  Hypeclass/Source/Schedule/ScheduleViewController.swift
  Hypeclass/Source/Search/SearchDetailCell.swift
  Hypeclass/Source/Search/SearchDetailViewController.swift
  Hypeclass/Source/Search/SearchViewController.swift
  Hypeclass/Source/Subscription/DancerCell.swift
  Hypeclass/Source/Subscription/SubscriptionViewController.swift
  Hypeclass/Source/WeeklyScheduleCell.swift
  Hypeclass/Util/Extension/UIImageView.swift
  Hypeclass/Util/ReusableComponent/DancerCell.swift
  Hypeclass/Util/ReusableComponent/IndicatorView.swift
  Hypeclass/Util/ReusableComponent/SearchBar.swift
  Hypeclass/Util/ReusableComponent/Separator.swift
Labels: 🧑🏻‍💻 지오, 🎨 UI

#107 [FEAT] SearchView 추천 TableView 적용
  Hypeclass.xcodeproj/project.pbxproj
  Hypeclass.xcodeproj/xcuserdata/gongtae.xcuserdatad/xcschemes/xcschememanagement.plist
  Hypeclass/API/Constant.swift
  Hypeclass/API/DanceClassManager.swift
  Hypeclass/API/DancerManager.swift
  Hypeclass/API/DancerService.swift
  Hypeclass/API/SearchManager.swift
  Hypeclass/API/StudioManager.swift
  Hypeclass/AppDelegate.swift
  Hypeclass/Assets.xcassets/DancerCoverImage.imageset/Contents.json
  Hypeclass/Assets.xcassets/DancerCoverImage.imageset/Mask group.png
  Hypeclass/Assets.xcassets/DancerInstagramImage.imageset/Contents.json
  Hypeclass/Assets.xcassets/DancerInstagramImage.imageset/image 54.png
  Hypeclass/Assets.xcassets/DancerProfileImage.imageset/Contents.json
  Hypeclass/Assets.xcassets/DancerProfileImage.imageset/Mask group.png
  Hypeclass/GoogleService-Info.plist
  Hypeclass/Model/DanceClass.swift
  Hypeclass/Model/Dancer.swift
  Hypeclass/Model/DancerDetailSchduleManager.swift
  Hypeclass/Model/DancerDetailScheduleModel.swift
  Hypeclass/Model/Studio.swift
  Hypeclass/Source/DancerDetailViewController.swift
  Hypeclass/Source/Main/MainViewController+DancerCell.swift
  Hypeclass/Source/Main/MainViewController+GenreCell.swift
  Hypeclass/Source/Main/MainViewController.swift
  Hypeclass/Source/MainTabController.swift
  Hypeclass/Source/Schedule/ScheduleViewController.swift
  Hypeclass/Source/Search/SearchDetailViewController.swift
  Hypeclass/Source/Search/SearchViewController.swift
  Hypeclass/Source/Subscription/SubscriptionViewController.swift
  Hypeclass/Source/WeeklyScheduleCell.swift
  Hypeclass/Util/ReusableComponent/DancerCell.swift
  Hypeclass/Util/ReusableComponent/IndicatorView.swift
  Hypeclass/Util/ReusableComponent/SearchBar.swift
  Hypeclass/Util/ReusableComponent/Separator.swift
Labels: 🧑🏻‍💻 치콩, 🎨 UI

#111 [FEAT] Firebase 로직 추가
  Hypeclass/API/DancerManager.swift
  Hypeclass/API/StudioManager.swift
  Hypeclass/Model/Dancer.swift
  Hypeclass/Source/Search/SearchViewController.swift
Labels: 🧑🏻‍💻 지오, 🌐 API

#112 merge Feature/schedule -> develop
  Hypeclass/Source/Schedule/ScheduleViewController.swift
Labels: 🧑🏻‍💻 루크, ↰ Merge

#113 merge Feature/subscription -> develop
  Hypeclass.xcodeproj/project.pbxproj
  Hypeclass/API/DancerManager.swift
  Hypeclass/API/StudioManager.swift
  Hypeclass/Source/Subscription/SubscriptionViewController.swift
  Hypeclass/Util/ReusableComponent/ItemCell.swift
Labels: 🧑🏻‍💻 루크, ↰ Merge

#114 merge Feature/firebase -> develop
  Hypeclass/API/DancerManager.swift
  Hypeclass/API/StudioManager.swift
  Hypeclass/Model/Dancer.swift
Labels: 🧑🏻‍💻 루크, ↰ Merge, 🚧 Conflict

#119 [FEAT] Firebase 전화번호 인증 로직, 회원가입 뷰 구현
  Hypeclass.xcodeproj/project.pbxproj
  Hypeclass/API/AuthManager.swift
  Hypeclass/Source/Auth/AuthOnboardViewController.swift
  Hypeclass/Source/Auth/AuthPhoneNumberViewController.swift
  Hypeclass/Source/Auth/AuthVerificationController.swift
  Hypeclass/Source/Auth/AuthViewController.swift
  Hypeclass/Util/Extension/UIColor.swift
  Hypeclass/Util/Extension/UITextField.swift
  Hypeclass/Util/ReusableComponent/CTAButton.swift
  Hypeclass/Util/ReusableComponent/ContainerTextField.swift
  Hypeclass/Util/ReusableComponent/SearchBar.swift
Labels: 🧑🏻‍💻 루크, 🎨 UI, 🌐 API

#117 [FEAT] MainViewController 구현
  Hypeclass.xcodeproj/project.pbxproj
  Hypeclass.xcodeproj/xcuserdata/gongtae.xcuserdatad/xcschemes/xcschememanagement.plist
  Hypeclass/API/Constant.swift
  Hypeclass/API/DanceClassManager.swift
  Hypeclass/API/DancerManager.swift
  Hypeclass/API/DancerService.swift
  Hypeclass/API/SearchManager.swift
  Hypeclass/API/StudioManager.swift
  Hypeclass/AppDelegate.swift
  Hypeclass/Assets.xcassets/DancerCoverImage.imageset/Contents.json
  Hypeclass/Assets.xcassets/DancerCoverImage.imageset/DancerCoverImage.png
  Hypeclass/Assets.xcassets/DancerCoverImage.imageset/Mask group.png
  Hypeclass/Assets.xcassets/DancerProfileImage.imageset/Contents.json
  Hypeclass/Assets.xcassets/DancerProfileImage.imageset/Mask group.png
  Hypeclass/GoogleService-Info.plist
  Hypeclass/Model/DanceClass.swift
  Hypeclass/Model/Dancer.swift
  Hypeclass/Model/DancerDetailSchduleManager.swift
  Hypeclass/Model/DancerDetailScheduleModel.swift
  Hypeclass/Model/Studio.swift
  Hypeclass/Source/DancerDetailView.swift
  Hypeclass/Source/DancerDetailViewController.swift
  Hypeclass/Source/Main/MainStudioCell.swift
  Hypeclass/Source/Main/MainViewController.swift
  Hypeclass/Source/Schedule/ScheduleViewController.swift
  Hypeclass/Source/Search/SearchDetailViewController.swift
  Hypeclass/Source/Search/SearchViewController.swift
  Hypeclass/Source/Subscription/SubscriptionViewController.swift
  Hypeclass/Source/WeeklyScheduleCell.swift
  Hypeclass/Util/ReusableComponent/DancerCell.swift
  Hypeclass/Util/ReusableComponent/IndicatorView.swift
  Hypeclass/Util/ReusableComponent/ItemCell.swift
  Hypeclass/Util/ReusableComponent/SearchBar.swift
  Hypeclass/Util/ReusableComponent/Separator.swift
Labels: 🧑🏻‍💻 지오, 🎨 UI, 🛠 Refactor, 🌐 API
