Repository DeveloperAcademy-POSTECH/MC3-Team3-Kongs, pull requests merged in 2022-08, with the labels that each got.

#124 [FEAT] Youtube Data API 를 받아온 후 Thumbnail과 제목 구현
  .gitignore
  Hypeclass.xcodeproj/project.pbxproj
  Hypeclass/API/Constant.swift
  Hypeclass/API/Helpers/Constant.swift
  Hypeclass/API/NetworkError.swift
  Hypeclass/API/NetworkManager.swift
  Hypeclass/Config/Constant.swift
  Hypeclass/Model/DancerDetailSchduleManager.swift
  Hypeclass/Model/YoutubeModelAPI.swift
  Hypeclass/Source/DancerDetailViewController.swift
  Hypeclass/Source/ThumbNailCell.swift
Labels: 🧑🏻‍💻 이안, 🎨 UI, 🌐 API

#122 [ADD] DanceClassDetailViewController 구현
  Hypeclass.xcodeproj/project.pbxproj
  Hypeclass/API/AuthManager.swift
  Hypeclass/Source/Auth/AuthOnboardViewController.swift
  Hypeclass/Source/Auth/AuthPhoneNumberViewController.swift
  Hypeclass/Source/Auth/AuthVerificationController.swift
  Hypeclass/Source/Auth/AuthViewController.swift
  Hypeclass/Source/DanceClassDetailViewController.swift
  Hypeclass/Util/Extension/UIColor.swift
  Hypeclass/Util/Extension/UITextField.swift
  Hypeclass/Util/ReusableComponent/CTAButton.swift
  Hypeclass/Util/ReusableComponent/ContainerTextField.swift
  Hypeclass/Util/ReusableComponent/SearchBar.swift
Labels: 🧑🏻‍💻 루크, 🎨 UI

#129 [FEAT] StudioViewController 구현
  Hypeclass.xcodeproj/project.pbxproj
  Hypeclass/API/StudioManager.swift
  Hypeclass/Model/Studio.swift
  Hypeclass/Source/Studio/StudioViewController.swift
  Hypeclass/Source/Studio/TabCell.swift
  Hypeclass/Source/Subscription/SubscriptionViewController.swift
  Hypeclass/Util/ReusableComponent/HeaderView.swift
  Hypeclass/Util/ReusableComponent/ItemCell.swift
Labels: 🧑🏻‍💻 지오, 🎨 UI, 🌐 API

#131 merge Feature/home -> develop
  Hypeclass.xcodeproj/project.pbxproj
  Hypeclass/API/StudioManager.swift
  Hypeclass/Source/Main/MainStudioCell.swift
  Hypeclass/Source/Main/MainViewController.swift
  Hypeclass/Source/Subscription/SubscriptionViewController.swift
Labels: 🧑🏻‍💻 루크, 🚧 Conflict

#138 [FEAT] 댄스 클래스 뷰 네트워크 연동 , 데이터 전처리
  Hypeclass/API/StudioManager.swift
  Hypeclass/Model/MockDataSet.swift
  Hypeclass/Model/Studio.swift
  Hypeclass/Source/DanceClassDetailViewController.swift
  Hypeclass/Util/Extension/Date.swift
Labels: 🧑🏻‍💻 루크, 🌐 API, 🗃 Model

#139 [FEAT] 전화번호 실기기 인증 테스트 성공, 사용자 입력 예외처리
  Hypeclass.xcodeproj/project.pbxproj
  Hypeclass/API/AuthManager.swift
  Hypeclass/API/SearchManager.swift
  Hypeclass/API/StudioManager.swift
  Hypeclass/AppDelegate.swift
  Hypeclass/Hypeclass.entitlements
  Hypeclass/Info.plist
  Hypeclass/Model/Studio.swift
  Hypeclass/Source/Auth/AuthPhoneNumberViewController.swift
  Hypeclass/Source/Auth/AuthVerificationController.swift
  Hypeclass/Source/DanceClassDetailViewController.swift
  Hypeclass/Source/Main/MainStudioCell.swift
  Hypeclass/Source/Main/MainViewController.swift
  Hypeclass/Source/Search/SearchDetailViewController.swift
  Hypeclass/Source/Studio/StudioViewController.swift
  Hypeclass/Source/Studio/TabCell.swift
  Hypeclass/Source/Subscription/SubscriptionViewController.swift
  Hypeclass/Util/Extension/UIColor.swift
  Hypeclass/Util/ReusableComponent/HeaderView.swift
  Hypeclass/Util/ReusableComponent/ItemCell.swift
Labels: 🧑🏻‍💻 루크, 🌐 API

#142 [CHORE] Kingfisher 추가
  Hypeclass.xcodeproj/project.pbxproj
Labels: 🧑🏻‍💻 루크, 📦 패키지

#141 [ADD] Reusable ScheduleItemCell 추가
  Hypeclass.xcodeproj/project.pbxproj
  Hypeclass/API/StudioManager.swift
  Hypeclass/Model/Studio.swift
  Hypeclass/Util/ReusableComponent/ScheduleItemCell.swift
  Hypeclass/Util/ReusableComponent/ScheduleItemView.swift
Labels: 🧑🏻‍💻 지오, 🎨 UI

#143 merge Feature/classdetail -> develop
  Hypeclass/API/StudioManager.swift
  Hypeclass/Model/MockDataSet.swift
  Hypeclass/Model/Studio.swift
  Hypeclass/Source/DanceClassDetailViewController.swift
  Hypeclass/Util/Extension/Date.swift
Labels: 🧑🏻‍💻 루크, ↰ Merge

#144 merge Feature/auth -> develop
  Hypeclass.xcodeproj/project.pbxproj
  Hypeclass/API/AuthManager.swift
  Hypeclass/AppDelegate.swift
  Hypeclass/Hypeclass.entitlements
  Hypeclass/Info.plist
  Hypeclass/Source/Auth/AuthOnboardViewController.swift
  Hypeclass/Source/Auth/AuthPhoneNumberViewController.swift
  Hypeclass/Source/Auth/AuthVerificationController.swift
Labels: 🧑🏻‍💻 루크, ↰ Merge

#145 [FEAT] ScheduleViewController POP-UP tag 추가
  Hypeclass.xcodeproj/project.pbxproj
  Hypeclass/API/AuthManager.swift
  Hypeclass/API/DancerManager.swift
  Hypeclass/API/SearchManager.swift
  Hypeclass/API/StudioManager.swift
  Hypeclass/Model/Dancer.swift
  Hypeclass/Model/Studio.swift
  Hypeclass/Source/Auth/AuthOnboardViewController.swift
  Hypeclass/Source/Auth/AuthPhoneNumberViewController.swift
  Hypeclass/Source/Auth/AuthVerificationController.swift
  Hypeclass/Source/Auth/AuthViewController.swift
  Hypeclass/Source/DanceClassDetailViewController.swift
  Hypeclass/Source/Main/MainStudioCell.swift
  Hypeclass/Source/Main/MainViewController.swift
  Hypeclass/Source/Schedule/ScheduleView.swift
  Hypeclass/Source/Schedule/ScheduleViewController.swift
  Hypeclass/Source/Search/SearchDetailViewController.swift
  Hypeclass/Source/Studio/StudioViewController.swift
  Hypeclass/Source/Studio/TabCell.swift
  Hypeclass/Source/Subscription/SubscriptionViewController.swift
  Hypeclass/Util/Extension/UIColor.swift
  Hypeclass/Util/Extension/UITextField.swift
  Hypeclass/Util/ReusableComponent/CTAButton.swift
  Hypeclass/Util/ReusableComponent/ContainerTextField.swift
  Hypeclass/Util/ReusableComponent/HeaderView.swift
  Hypeclass/Util/ReusableComponent/ItemCell.swift
  Hypeclass/Util/ReusableComponent/SearchBar.swift
Labels: 🧑🏻‍💻 지오, 🎨 UI

#146 merge -> Feature/studio develop
  Hypeclass.xcodeproj/project.pbxproj
  Hypeclass/API/StudioManager.swift
  Hypeclass/Model/Studio.swift
  Hypeclass/Source/Main/MainViewController.swift
  Hypeclass/Source/Studio/StudioEventCell.swift
  Hypeclass/Source/Studio/StudioEventViewController.swift
  Hypeclass/Source/Studio/StudioViewController.swift
  Hypeclass/Util/ReusableComponent/ScheduleItemCell.swift
  Hypeclass/Util/ReusableComponent/ScheduleItemView.swift
Labels: 🧑🏻‍💻 루크, ↰ Merge, 🚧 Conflict

#147 merge Feature/schedule -> develop
  Hypeclass/Source/Schedule/ScheduleView.swift
  Hypeclass/Source/Schedule/ScheduleViewController.swift
Labels: 🧑🏻‍💻 루크, ↰ Merge

#151 [FEAT] introduce View 구현
  Hypeclass.xcodeproj/project.pbxproj
  Hypeclass/API/AuthManager.swift
  Hypeclass/API/SearchManager.swift
  Hypeclass/API/StudioManager.swift
  Hypeclass/AppDelegate.swift
  Hypeclass/Hypeclass.entitlements
  Hypeclass/Info.plist
  Hypeclass/Model/MockDataSet.swift
  Hypeclass/Model/Studio.swift
  Hypeclass/Source/Auth/AuthOnboardViewController.swift
  Hypeclass/Source/Auth/AuthPhoneNumberViewController.swift
  Hypeclass/Source/Auth/AuthVerificationController.swift
  Hypeclass/Source/Auth/AuthViewController.swift
  Hypeclass/Source/DanceClassDetailViewController.swift
  Hypeclass/Source/Main/MainStudioCell.swift
  Hypeclass/Source/Main/MainViewController+DancerCell.swift
  Hypeclass/Source/Main/MainViewController+GenreCell.swift
  Hypeclass/Source/Main/MainViewController.swift
  Hypeclass/Source/Schedule/ScheduleView.swift
  Hypeclass/Source/Schedule/ScheduleViewController.swift
  Hypeclass/Source/Search/SearchDetailViewController.swift
  Hypeclass/Source/Studio/IntroduceDancerCell.swift
  Hypeclass/Source/Studio/IntroduceViewController.swift
  Hypeclass/Source/Studio/RecentVideoCell.swift
  Hypeclass/Source/Studio/StudioEventCell.swift
  Hypeclass/Source/Studio/StudioEventViewController.swift
  Hypeclass/Source/Studio/StudioViewController.swift
  Hypeclass/Source/Studio/TabCell.swift
  Hypeclass/Source/Subscription/SubscriptionViewController.swift
  Hypeclass/Util/Extension/Date.swift
  Hypeclass/Util/Extension/UIColor.swift
  Hypeclass/Util/Extension/UITextField.swift
  Hypeclass/Util/Extension/UIViewController.swift
  Hypeclass/Util/ReusableComponent/CTAButton.swift
  Hypeclass/Util/ReusableComponent/ContainerTextField.swift
  Hypeclass/Util/ReusableComponent/HeaderView.swift
  Hypeclass/Util/ReusableComponent/ItemCell.swift
  Hypeclass/Util/ReusableComponent/ScheduleItemCell.swift
  Hypeclass/Util/ReusableComponent/ScheduleItemView.swift
  Hypeclass/Util/ReusableComponent/SearchBar.swift
Labels: 🧑🏻‍💻 치콩, 🎨 UI

#152 [FEAT] 스튜디오 디테일 뷰 스케줄 탭 연결
  Hypeclass.xcodeproj/project.pbxproj
  Hypeclass/Source/Studio/StudioScheduleViewController.swift
  Hypeclass/Source/Studio/StudioViewController.swift
  Hypeclass/Source/Subscription/SubscriptionViewController.swift
  Hypeclass/Util/ReusableComponent/ScheduleItemView.swift
Labels: 🧑🏻‍💻 지오, 🛠 Refactor

#153 [FEAT] 메인화면 네트워크 연동, 앱 로고, 아이콘 추가
  Hypeclass.xcodeproj/project.pbxproj
  Hypeclass/API/Constant.swift
  Hypeclass/API/EventManager.swift
  Hypeclass/Assets.xcassets/AppIcon.appiconset/1024.png
  Hypeclass/Assets.xcassets/AppIcon.appiconset/120-1.png
  Hypeclass/Assets.xcassets/AppIcon.appiconset/120.png
  Hypeclass/Assets.xcassets/AppIcon.appiconset/180.png
  Hypeclass/Assets.xcassets/AppIcon.appiconset/40.png
  Hypeclass/Assets.xcassets/AppIcon.appiconset/58.png
  Hypeclass/Assets.xcassets/AppIcon.appiconset/60.png
  Hypeclass/Assets.xcassets/AppIcon.appiconset/80.png
  Hypeclass/Assets.xcassets/AppIcon.appiconset/87.png
  Hypeclass/Assets.xcassets/AppIcon.appiconset/Contents.json
  Hypeclass/Assets.xcassets/logo.imageset/1024.png
  Hypeclass/Assets.xcassets/logo.imageset/180-1.png
  Hypeclass/Assets.xcassets/logo.imageset/80.png
  Hypeclass/Assets.xcassets/logo.imageset/Contents.json
  Hypeclass/Model/Event.swift
  Hypeclass/Source/DanceClassDetailViewController.swift
  Hypeclass/Source/Main/MainViewController.swift
  Hypeclass/Source/Schedule/ScheduleView.swift
  Hypeclass/Source/Schedule/ScheduleViewController.swift
Labels: 🧑🏻‍💻 루크, 🎨 UI, 🌐 API

#155 [FEAT] SearchDetail -> 뷰 연결
  Hypeclass/API/StudioManager.swift
  Hypeclass/Source/DancerDetailViewController.swift
  Hypeclass/Source/Search/SearchDetailViewController.swift
Labels: 🧑🏻‍💻 치콩, 🎨 UI, 🌐 API

#156 [REFACTOR] 댄서 디테일 뷰 수정 및 기능 구현
  Hypeclass.xcodeproj/project.pbxproj
  Hypeclass/Source/DancerDetailViewController.swift
  Hypeclass/Source/Main/MainViewController+DancerCell.swift
  Hypeclass/Source/Main/MainViewController+GenreCell.swift
  Hypeclass/Source/Schedule/ScheduleViewController.swift
  Hypeclass/Source/Studio/IntroduceDancerCell.swift
  Hypeclass/Source/Studio/IntroduceViewController.swift
  Hypeclass/Source/Studio/RecentVideoCell.swift
  Hypeclass/Source/Studio/StudioViewController.swift
  Hypeclass/Source/Subscription/SubscriptionViewController.swift
  Hypeclass/Util/Extension/UIViewController.swift
  Hypeclass/Util/ReusableComponent/HeaderView.swift
  Hypeclass/Util/ReusableComponent/ScheduleItemView.swift
Labels: 🧑🏻‍💻 지오, 🎨 UI, 🛠 Refactor, 🌐 API

#157 2th 스프린트 마무리 작업 - View 간 integration, 에러 수정, 네트워크 연결.
  Hypeclass.xcodeproj/project.pbxproj
  Hypeclass/API/DanceClassManager.swift
  Hypeclass/API/EventManager.swift
  Hypeclass/Model/DanceClass.swift
  Hypeclass/Model/MockDataSet.swift
  Hypeclass/Source/Auth/AuthOnboardViewController.swift
  Hypeclass/Source/DanceClassDetailViewController.swift
  Hypeclass/Source/DancerDetailViewController.swift
  Hypeclass/Source/Main/MainStudioCell.swift
  Hypeclass/Source/Main/MainViewController.swift
  Hypeclass/Source/MainTabController.swift
  Hypeclass/Source/Schedule/ScheduleView.swift
  Hypeclass/Source/Schedule/ScheduleViewController.swift
  Hypeclass/Source/Search/SearchDetailViewController.swift
  Hypeclass/Source/Studio/IntroduceDancerCell.swift
  Hypeclass/Source/Studio/IntroduceViewController.swift
  Hypeclass/Source/Studio/StudioEventCell.swift
  Hypeclass/Source/Studio/StudioEventViewController.swift
  Hypeclass/Source/Studio/StudioScheduleViewController.swift
  Hypeclass/Source/Studio/StudioViewController.swift
  Hypeclass/Source/Subscription/SubscriptionViewController.swift
  Hypeclass/Util/Extension/UIApplication.swift
  Hypeclass/Util/Extension/UIPageViewController.swift
  Hypeclass/Util/ReusableComponent/HeaderView.swift
  Hypeclass/Util/ReusableComponent/ItemCell.swift
  Hypeclass/Util/ReusableComponent/ScheduleItemCell.swift
  Hypeclass/Util/ReusableComponent/ScheduleItemView.swift
Labels: 🧑🏻‍💻 루크, 🐛 Debug, 🎨 UI, 🌐 API
